cache:
  paths:
  - node_modules/


stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - bash deploy git.jinwanzhilin.com/liubing/nodeclub.git jiuyanlou
    - bash makeproject jiuyanlou build
  tags:
    - jinwan-ci

job_test:
  stage: test
  script:
    - bash makeproject jiuyanlou test-cov
  tags:
    - jinwan-ci

job_deploy_staging:
  stage: deploy
  script:
    - bash restart jiuyanlou app.js
    - bash npmrun apidoc jiuyanlou
    - bash npmrun todo jiuyanlou
  environment:
      name: staging
      url: http://www.jiuyanlou.com
  only:
    - master
  tags:
    - jinwan-ci
