cache:
  paths:
  - node_modules/


stages:
  - build
  - test
  - deploy

#test:
#  stage: test
#  only:
#      - master
#  script:
#    - deploy 47.52.20.174/jinwan/laibijia.git laibijia
#    - ./node_modules/.bin/istanbul cover _mocha
#  tags:
#    - jinwan-ci
build:
  stage: build
  script:
    - deploy 47.52.20.174/liubing/nodeclub.git jiuyanlou
    - makeproject jiuyanlou build
  tags:
    - jinwan-ci

test:
  stage: test
  script:
    - makeproject jiuyanlou test-cov
  tags:
    - jinwan-ci

deploy_staging:
  stage: deploy
  script:
    - restart jiuyanlou app.js
    - npmrun apidoc jiuyanlou
    - npmrun todo jiuyanlou
  environment:
      name: staging
      url: http://www.jiuyanlou.com
  only:
    - master
  tags:
    - jinwan-ci
