cache:
  paths:
  - node_modules/


stages:
  - build
  - test
  - deploy

job_build:
  stage: build
  script:
    - cd /home/jiuyanlou && git fetch && git reset --hard origin/master && npm install
    - make build
  tags:
    - jinwan-ci

job_test:
  stage: test
  script:
    - cd /home/jiuyanlou
    - make test-cov
  tags:
    - jinwan-ci

job_deploy_staging:
  stage: deploy
  script:
    - cd /home/jiuyanlou
    - forever stop app.js
    - forever start app.js
    - npm run apidoc
    - npm run todo
  environment:
      name: staging
      url: http://www.jiuyanlou.com
  only:
    - master
  tags:
    - jinwan-ci
