cache:
  paths:
  - node_modules/


stages:
  - test
  - eslint
  - deploy

#test:
#  stage: test
#  only:
#      - master
#  script:
#    - deploy 47.52.20.174/jinwan/laibijia.git laibijia
#    - ./node_modules/.bin/istanbul cover _mocha
#  tags:
#    - jinwan-ci

deploy:
  stage: deploy
  script:
    - deploy 47.52.20.174/liubing/nodeclub.git jiuyanlou
    - restart jiuyanlou app
    - apidoc jiuyanlou
    - npm run todo
  only:
    - master
  tags:
    - jinwan-ci
